config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :users
  root 'login#loginask'
  post 'new_like', to: 'games#new_like'
  get 'match', to: 'games#match'

  # Login
   get 'login', to: "login#loginask"
   post 'login/validate'
   delete 'login/logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :user
    enum platform: [:pc, :xbox, :ps3, :nint_switch]
    enum category: [:action, :adventure, :rpg, :sport, :shoot, :fight, :other]
end

app/models/like.rb
class Like < ApplicationRecord
  

end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :nickname,  presence: true
  validates :password,  presence: true, :on => :create
  validates :mail, presence: true, format: { with: VALID_EMAIL_REGEX }
  def self.login(mail, password)
    user = User.find_by_mail(mail)
    user_aux = User.find_by_password(password)
    if mail.blank?
      return nil, "Debes ingresar un e-mail"
    elsif user != user_aux
      return nil, "Usuario o clave incorrecto"
  elsif user == nil
        return nil, 'El usuario no existe'
    else
      return user, nil
    end
  end

  def games
      Game.where(user_id: self.id).all
  end

  def not_my_games
    Game.where.not(user_id: self.id).all
  end

  def active_toggle
    self.update(active: !self.active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :user_session_set

  def user_session_set
    user_id = session[:user_id]
    if User.exists?(user_id)
      user = User.find(user_id)
      @current_user = user
    else
      @current_user = nil
    end
  end

  def user_session_required
    user_session_set
    if !@current_user || !@current_user.active
      session[:user_id] = nil
      @current_user = nil
      redirect_to login_path
      return
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    if session[:user_id] != nil
        @game = Game.new
    else
        redirect_to root_path
    end
  end

  def new_like
      game_id = params[:game_id].to_i
      game = Game.find(game_id)
      likes = Like.where(liker: game.user_id, liked: session[:user_id])

      if likes.nil? || likes.blank?
          n = Like.new({liker: session[:user_id], liked: game.user_id, game: game.id})
          n.save
      else
          redirect_to action: 'match', controller: 'games', params: {new_game: likes[0].game, old_game: game.id, exchanger: game.user_id}
      end
  end

  def match
      @me = User.find(session[:user_id]).name
      @other = User.find(params[:exchanger]).name
      @mail = User.find(params[:exchanger]).mail
      @new_game = Game.find(params[:new_game]).name
      @old_game = Game.find(params[:old_game]).name
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.user_id = session[:user_id]

    respond_to do |format|
      if @game.save
        format.html { redirect_to user_path(session[:user_id]), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      parm = params.require(:game).permit(:name, :description, :platform, :category)
      parm[:platform] = parm[:platform].to_i
      parm[:category] = parm[:category].to_i
      parm
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def add_like
    
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  #skip_before_action :user_session_required, only: [:validate]

  def loginask
    user_id = session[:user_id]
    if !user_id.nil? && User.exists?(user_id)
      redirect_to user_path(user_id)
    end
  end

  def validate
    mail = params[:mail]
    password = params[:password]
    user, @error = User.login(mail, password)
    if @error
      render 'loginask'
    else
      session[:user_id] = user.id
      redirect_to root_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :nickname, :mail, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "4.7.0"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<div class="login-page" >
  <div class="form">
  <%= form_for(game) do |f| %>
    <% if game.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

        <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field" style="color: white">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field" style="color: white">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>

    <div class="field" style="color: white">
      <%= f.label :platform %>
      <%= select :game, :platform, Game.platforms %>
    </div>

    <div class="field" style="color: white">
        <%= f.label :category %>
        <%= select :game, :category, Game.categories %>
    </div>

    <div class="actions" style="color: white">
      <%= f.submit %>
    </div>
  <% end %>
  <% if @error.present? %>
    <div class="error-message"><strong>Atención: </strong><%= @error %></div>
  <% end %>
  </div>
</div>

app/views/games/edit.html.erb
<center><h1>Editing Game</h1></center>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<!-- <p id="notice"><%= notice %></p> -->
<div class="icon-bar">
  <a class="active" href="#"><img class='logo'></a>
  <a href="#"><img class='nintendo'></a>
  <a href="#"><img class='playstation'></a>
  <!--<a href="#"><img class='windows'></a>-->
  <a href="#"><img class='xbox'></a>
    <%= link_to '<i class="fa fa-user" style="font-size:30px;"></i>'.html_safe, user_path(session[:user_id]) %>
    <%= link_to '<i class="fa fa-sign-out" style="font-size:30px;"></i>'.html_safe, login_logout_path, method: :delete  %>
</div>


<div id="columns">

    <% User.find(session[:user_id]).not_my_games.each do |game| %>

        <figure>
            <img src=<%=game.description %> >
            <figcaption>
                <%= game.name %>
            </figcaption>
            <figcaption>
              <%= button_tag(:class => "button button1", action: 'new_like', id: game.id) do %>
                <i class='fa fa-thumbs-up'></i>
              <% end %>

              <%= button_tag( :class => "button button2") do %>
                <i class="fa fa-thumbs-down"></i>
              <% end %>

            </figcaption>
        </figure>

    <% end %>
</div>


<br>

app/views/games/match.html.erb
<div class="icon-bar">
  <a class="active" href="#"><img class='logo'></a>
  <a href="#"><img class='nintendo'></a>
  <a href="#"><img class='playstation'></a>
  <!--<a href="#"><img class='windows'></a>-->
  <a href="#"><img class='xbox'></a>
    <%= link_to '<i class="fa fa-user" style="font-size:30px;"></i>'.html_safe, user_path(session[:user_id]) %>
    <%= link_to '<i class="fa fa-sign-out" style="font-size:30px;"></i>'.html_safe, login_logout_path, method: :delete  %>
</div>
<center><h1><%= @me %> hiciste match con <%= @other %></h1>

<h2>Tienes que intercambiar tu juego <%= @old_game %> con el juego <%= @new_game %> de tu match.</h2>

<p>El mail de tu match es <%= @mail %></p>
</center>

app/views/games/new.html.erb
<div class="icon-bar">
  <a class="active" href="#"><img class='logo'></a>
  <a href="#"><img class='nintendo'></a>
  <a href="#"><img class='playstation'></a>
  <!--<a href="#"><img class='windows'></a>-->
  <a href="#"><img class='xbox'></a>
    <%= link_to '<i class="fa fa-user" style="font-size:30px;"></i>'.html_safe, user_path(session[:user_id]) %>
    <%= link_to '<i class="fa fa-sign-out" style="font-size:30px;"></i>'.html_safe, login_logout_path, method: :delete  %>
</div>

<center><h1>New Game</h1></center>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Image:</strong>
  <br>
  <%= image_tag @game.description, style: 'width: 20%; height: 20%' %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', user_path(@game.user_id) %>

app/views/layouts/_close_view.html.erb
  <nav >
    <%=if @current_user.nil?
      link_to "Registrarse", new_user_path
    else
      link_to "Cerrar sesion", login_logout_path, method: :delete
        end%>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One4onegames</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'like', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>


  <body>

    <%= yield %>
  </body>
</html>

app/views/login/loginask.html.erb
<header >
  <%= render "layouts/close_view" %>
</header>

<body style="background-color: #10222b;">
<div class="login-page" >
  <center>
    <img class= "biglogo"/>
  </center>
  <div class="form">
    <%= form_tag login_validate_path do %>
    <div class="login-control">
      <%= text_field_tag(:mail, nil, placeholder: "email") %>
      <%= password_field_tag(:password, nil, placeholder: "password") %>
    </div>
    <div class="form-control1">
      <%= submit_tag("Ingresar", :style => "background: #bdd684;") %>
    </div>
  <% end %>
  <% if @error.present? %>
    <div class="error-message"><strong>Atención: </strong><%= @error %></div>
  <% end %>
  </div>
</div>
</body>

<style>

</style>

app/views/users/_form.html.erb
<!--<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <div class="field">
    <%= f.label :mail %>
    <%= f.text_field :mail %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

-->



<div class="login-page" >
  <div class="form">
    <%= form_for(user) do |f| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <div class="login-control">
      <div class="field" style="color: white">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field" style="color: white">
        <%= f.label :nickname %>
        <%= f.text_field :nickname %>
      </div>

      <div class="field" style="color: white">
        <%= f.label :mail %>
        <%= f.text_field :mail %>
      </div>

      <div class="field" style="color: white">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>

    </div>
    <div class="form-control1">
      <%= submit_tag("Ingresar", :style => "background: #bdd684;") %>
    </div>
  <% end %>
  <% if @error.present? %>
    <div class="error-message"><strong>Atención: </strong><%= @error %></div>
  <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="icon-bar">
  <a class="active" href="#"><img class='logo'></a>
  <a href="#"><img class='nintendo'></a>
  <a href="#"><img class='playstation'></a>
  <!--<a href="#"><img class='windows'></a>-->
  <a href="#"><img class='xbox'></a>
    <%= link_to '<i class="fa fa-user" style="font-size:30px;"></i>'.html_safe, user_path(session[:user_id]) %>
    <%= link_to '<i class="fa fa-sign-out" style="font-size:30px;"></i>'.html_safe, login_logout_path, method: :delete  %>
</div>

<center><h1>Editing User</h1></center>

<%= render 'form', user: @user %>

<!-- <%= link_to 'Show', @user %> | -->
<%= link_to 'Back', user_path(@user) %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Nickname</th>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.nickname %></td>
        <td><%= user.mail %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Registrate! :D</h1>

<%= render 'form', user: @user %>

<%= link_to 'Inicio', users_path %>

app/views/users/show.html.erb
<div class="icon-bar">
  <a class="active" href="#"><img class='logo'></a>
  <a href="#"><img class='nintendo'></a>
  <a href="#"><img class='playstation'></a>
  <!--<a href="#"><img class='windows'></a>-->
  <a href="#"><img class='xbox'></a>
    <%= link_to '<i class="fa fa-user" style="font-size:30px;"></i>'.html_safe, user_path(session[:user_id]) %>
    <%= link_to '<i class="fa fa-sign-out" style="font-size:30px;"></i>'.html_safe, login_logout_path, method: :delete  %>
</div>
<p id="notice"><%= notice %></p>

<p>
  <center>
  <strong>
  <%= @user.name %>'s Profile
  </strong>
</center>
</p>

<div class=container>
  <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_game_path %>
  <%= link_to 'Edit Profile', edit_user_path(@user) %>
</div>


<center>
<img src="https://press.my.com/media/redactor/Logo_04.png" style="width:140px;height:auto;">
</center>



<div id="columns">

    <% @user.games.each do |game|%>

        <figure>
            <img src=<%=game.description %> >
            <figcaption>
                <%= game.name %>
            </figcaption>
        </figure>

    <% end %>
</div>
<br>
<%= link_to 'Add Game', new_game_path %>
<br>


<%= link_to 'Edit Profile', edit_user_path(@user) %>

<br>

<%= link_to 'Home', games_path(@user)%>